version: '3'

networks:
  laravel:

services:
  nginx:
    image: nginx:stable-alpine
    container_name: ${APP_NAME:-laravel}_nginx
    ports:
      - "80:80"
    volumes:
      - .:/app
      - .docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
      - mysql
    networks:
      - laravel

  mysql:
    container_name: ${APP_NAME:-laravel}_mysql
    image: mysql:8.0
    restart: unless-stopped
    tty: true
    ports:
      - "3306:3306"
    volumes:
      - .docker/mysql/storage:/var/lib/mysql
      - .docker/mysql/init:/docker-entrypoint-initdb.d/
      - .docker/mysql/my.cnf:/etc/mysql/conf.d/my.cnf
    environment:
      MYSQL_DATABASE: ${APP_NAME:-laravel}
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: secret
    networks:
      - laravel

  app:
    build:
     context: .
     dockerfile: .docker/php/Dockerfile
     args:
      - UID=${UID:-1000}
      - GID=${GID:-1000}
    container_name: ${APP_NAME:-laravel}_app
    volumes:
      - .:/app
    ports:
      - "9000:9000"
    networks:
      - laravel

  redis:
    image: redis:latest
    container_name: ${APP_NAME:-laravel}_redis
    tty: true
    volumes:
      - .docker/redis/storage:/data
    ports:
      - 6379:6379
    networks:
      - laravel